### ISSUE TITLE
Erro ?

### ISSUE THREAD

**Issue by v0Lcoom** [dahquan/rattlesnake#11]
what would this error ?
https://gyazo.com/f34e4fe618cd0693712a1639eae6f09e
it seems that bots do not follow me , and hardly find them on the server .

**Comment by dahquan** [comment]
That means some of the proxy servers you are using are not able to connect. And if you are surrounded by alot other snakes they are most likely not going to make it to you. Sometimes they take a while to get there cause they keep dying.

**Comment by v0Lcoom** [comment]
It is to know how many bots have on the server ?

**Comment by dahquan** [comment]
It says the amount of bots that will spawn after you connect. The bot script isn't as advanced as it's only an example, feel free to edit it and submit any changes you think should be made.

**Comment by dahquan** [comment]
Please take a look at the [F.A.Q](https://github.com/dahquan/rattlesnake/blob/master/FAQ.md).
