### ISSUE TITLE
Bot count function?

### ISSUE THREAD

**Issue by YTpuffer** [dahquan/rattlesnake#12]
Is there anything done yet on a bot count function?
Let me know

**Comment by dahquan** [comment]
No there isn't, this project is meant to be just a library. It isn't specifically made for botting, I am however working on another project that will be dedicated too it.

Feel free to edit the example and add in any extra functionality.

**Comment by dahquan** [comment]
Added in 8de9c13a96fb081c2731e306dddcd392ae44e2eb
