### ISSUE TITLE
bots don't launch problem server

### ISSUE THREAD

**Issue by Wartoz** [dahquan/rattlesnake#13]
XMLHttpRequest cannot load http://tsukigro-tsukigro.c9users.io:8080/inject. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://slither.io' is therefore not allowed access.
Bots don't start here some screenshots :
http://i.imgur.com/PjrAwqC.png cannot get page
http://i.imgur.com/yIUxbuK.png code inject
http://i.imgur.com/oXQpsu8.jpg error in slither 
http://i.imgur.com/7RoEx48.png c9 workspace 

someone knows how to fix that please?

**Comment by RaxBoon** [comment]
wartoz you have the agar.io bots

**Comment by dahquan** [comment]
Your first picture shows a url without the :8080 port and the other ones show it. Are you sure you're using the right url?

**Comment by Wartoz** [comment]
fixed bro

**Comment by Wartoz** [comment]
i mooved to other vps
