### ISSUE TITLE
Bot count function! 

### ISSUE THREAD

**Issue by YTpuffer** [dahquan/rattlesnake#14]
I already have an idea how to do this but i cant figure out how:

      bot.on('spawn', function() {
        console.log(bot.name + 'spawned')
    
     bot.on('dead', function() {
        console.log(bot.name + ' died')

Amount of working bots = Spawned bots - Dead Bots

But where can i get the amount of spawned bots/dead bots?

**Comment by YTpuffer** [comment]
function botcount
 console.log ('Bots:' +(spawn - dead)

This isnt working (Ofcourse) any other way i can find the amount of spawned bots and dead bots

**Comment by SrNicolas** [comment]
simple. a variable

**Comment by YTpuffer** [comment]
Explain me please?

**Comment by SrNicolas** [comment]
u did thumbs down on mah comment, not going 2 explain, 2 fab 4 u

**Comment by mayed505** [comment]
a like from me please explain to me on skype if you would like haha.

**Comment by mayed505** [comment]
How i would think is this code:
`
var Alive = (Some Variable)
var Dead = (Some Variable)
Fuction BotCount() {
console.log ('Bots:' + Alive + '/' +  Dead);
}, 100);
`
Correct me if im thinking wrong :)
