### ISSUE TITLE
change bot skin possible?

### ISSUE THREAD

**Issue by Wartoz** [dahquan/rattlesnake#16]
there is a command to set up a skin in the console tab : setSkin(snake, 25) someone knows how to set up this command for bots?

**Comment by DeRpYsApLiNg** [comment]
I'll look into it for you ;c

**Comment by RuneBots** [comment]
Not easy, iTwigX. All I know is that it has something to do with packets.

**Comment by mayed505** [comment]
@RuneBots its easy i can change skins in the config on dlist/bot.js we can use  setSkin (skinpacketit)

**Comment by dahquan** [comment]
Take a look at 3e02508, bots will now use the same skin you choose or optionally you can set one at the top of the script.
