### ISSUE TITLE
Feedme.js problem error

### ISSUE THREAD

**Issue by mayed505** [dahquan/rattlesnake#19]
i get this error when playing https://gyazo.com/b64c1a5802aaf6045294a7eaa956cbf2

**Comment by sandor111** [comment]
How many proxies were you using?

**Comment by mayed505** [comment]
1902 proxies

**Comment by gamer2510** [comment]
Ur skype?

**Comment by dahquan** [comment]
Those errors are due to some proxies not being able to connect.

**Comment by Dejerne** [comment]
@mayed505 Where u get your proxies from?

**Comment by mayed505** [comment]
@Dejerne premium.freeproxy.ru/en/

**Comment by dahquan** [comment]
Please take a look at the [F.A.Q](https://github.com/dahquan/rattlesnake/blob/master/FAQ.md).
