### ISSUE TITLE
please include uuid and stuff so other people can connect to the feeder

### ISSUE THREAD

**Issue by sandor111** [dahquan/rattlesnake#21]
Can some one tell me how to use this on a vps. Or just let my bots connect to some one.

**Comment by dahquan** [comment]
The snake needs your current position to go to you, it can't find you by uuid.

**Comment by RuneBots** [comment]
Sorry, but I aint gonna help you. Why? You use a opensource, and you sell it for 12 dollars....

**Comment by SrNicolas** [comment]
XDDDDDDDDDD

**Comment by sandor111** [comment]
@RuneBots you never helped any one enige wat je kan is met kk schelden

**Comment by mayed505** [comment]
@RuneBots to be honest you did that too you started trying to sell your agario bots with "" Open Source "" why are you targeting him?

**Comment by kurama129** [comment]
Fuck off rune

**Comment by RuneBots** [comment]
"opensource"? It was full editted.... Full custom code...

**Comment by kurama129** [comment]
then make uuid yourself instead of begging someone to do it for you now fuckoff

**Comment by SrNicolas** [comment]
@kurama129 wtf, why are you so toxic? Have the world done something horrible to you?

**Comment by kurama129** [comment]
im not toxic, people like you ,rune and sam sell free bots for money thats why i hate you guys btw stop asking here for you meybots shit and make it urself

**Comment by SrNicolas** [comment]
Well. When meybots was active, i got my OWN bots, with my OWN IPN system and OWN extension.

And now I'm looking at rattlesnake for the buffers to make my OWN slither bots with my OWN IPN system and ,y OWN extension , so stop all the hate to me cuz I didn't steal code when meybots was in development.

**Comment by kurama129** [comment]
but still.......... you did
