### ISSUE TITLE
Bots stay at a low amount

### ISSUE THREAD

**Issue by ravyn120** [dahquan/rattlesnake#23]
I'm using 200 private proxies the bot amount stays low like at 10 there are no errors.

**Comment by dahquan** [comment]
Are you looking at the Bot Alive count that was just added? I found a bug in it that I'm fixing that is displaying the wrong number.

**Comment by ravyn120** [comment]
No i'm looking at a custom bot counter that shows how many were connected not alive

**Comment by dahquan** [comment]
I see what you're talking about, I'll look into it. Out of the 200, about how many connect?

**Comment by ravyn120** [comment]
About 10-12

**Comment by dahquan** [comment]
Really? I'm testing with 120 and get about 100. Are you running it on your local pc?

**Comment by ravyn120** [comment]
I tested it with my pc and on c9.io and with a vps.

**Comment by dahquan** [comment]
Can you paste your custom counter here? And it could also be that your network can't handle it

**Comment by ravyn120** [comment]
@dahquan yeah it might be my network. Give me a second i'm going to check my usage when ever I run the bots

**Comment by Wartoz** [comment]
it's working perfect with vps but how you did to set up on c9 bro? i tried but i failed i mooved to koding vm

**Comment by ravyn120** [comment]
@Wartoz make the c9.io workspace public because if its not it cannot access the link/inject or whatever.

**Comment by ravyn120** [comment]
Ehh I fixed it by adding like 7k public proxies still only get like 250 out of 7.3k proxies but what ever i'm getting 250

**Comment by sandor111** [comment]
How to run the bots on a vps???
