### ISSUE TITLE
Recode feedme.js in socket.io or websocket

### ISSUE THREAD

**Issue by SrNicolas** [dahquan/rattlesnake#24]
Hi. as xhttp is a little unefficient, could you do a websocket connection from feedme.js and a tampermonkey script (I could do that) because websocket is very fast and allows 2 clients spawning in bots :)

**Comment by dahquan** [comment]
Yes I can put it in WebSockets, I was initially going to do this but then again it's just an example. This repository isn't dedicated to feedme.js, I'm working on a completely new project dedicated to the bot and it supports the websockets. It's going to be released in another day or 2.

**Comment by SrNicolas** [comment]
Thanks for the info.
