### ISSUE TITLE
Create UUIDS for feeder

### ISSUE THREAD

**Issue by mayed505** [dahquan/rattlesnake#25]
Please create UUIDs for feeder so i can access my vps bots without everytime changing my ip since my ISP changes my ip address every 6 hours. Just like ogar-feeder-bot

**Comment by HLDahquan** [comment]
The bot doesn't find you based on ip... it finds you based on your position that you send to the server. This project isn't made for a feeding bot, I'm working on a project dedicated to it and should be released in 2-3 days.

**Comment by mayed505** [comment]
@HLDahquan Alright. awesome

**Comment by ravyn120** [comment]
@mayed505 use a dns with and auto ip updater or whatever
