### ISSUE TITLE
Trying to create bot counter on dev console

### ISSUE THREAD

**Issue by mayed505** [dahquan/rattlesnake#26]
Hello @dahquan im trying to console log bots alive with INJECT code heres what im trying
`const INJECT =  "(function() {\r\n" +
"    var intv = 0;\r\n" +
"    var playClick = play_btn.elem.onclick;\r\n" +
"    var lastState = want_close_socket;\r\n" +
"    var oldConnect = connect;\r\n" +
"    function get(path) {\r\n" +
"        var xhttp = new XMLHttpRequest();\r\n" +
"        xhttp.open(\"GET\", \"http://127.0.0.1:1337/\" + path, true);\r\n" +
"        xhttp.send();\r\n" +
"    }\r\n" +
"    function start() {\r\n" +
"        intv = setInterval(function() {\r\n" +
"            if (snake) {\r\n" +
"                if (typeof fetch !== 'undefined') {\r\n" +
"                    get('goto?x=' + snake.xx + '&&y=' + snake.yy);\r\n" +
"                }\r\n" +
"            }\r\n" +
"        }, 1000);\r\n" +
"        window.onkeydown = function(e) {\r\n" +
"            if (e.keyCode === 88) {\r\n" +
"                get('speed/on');\r\n" +
"            }\r\n" +
"        };\r\n" +
"        window.onkeyup = function(e) {\r\n" +
"            if (e.keyCode === 88) {\r\n" +
"                get('speed/off');\r\n" +
"            }\r\n" +
"        };\r\n" +
"    }\r\n" +
"    function stop() {\r\n" +
"        clearInterval(intv);\r\n" +
"    }\r\n" +
"    play_btn.elem.onclick = function() {\r\n" +
"        start();\r\n" +
"        playClick();\r\n" +
"    };\r\n" +
"    window.connect = function() {\r\n" +
"        oldConnect();\r\n" +
"        get('server/' + bso.ip + ':' + bso.po + '?skin=' + localStorage.snakercv);\r\n" +
"        forceServer(bso.ip, bso.po);\r\n" +
"        window.connect = oldConnect;\r\n" +
"    }\r\n" +
"    console.log('You can start the bots now by logging in');\r\n" +
"    console.log('* Changing servers is not supported');\r\n" +
"    console.log('[Bots Alive: ' + Alives + ']\t\t' + msg);\r\n" +    //<<<-- Here trying to console log
"})();\r\n";

// TODO: Handle unknown problems in bot
process.on('uncaughtException', function(err) { console.log(err) })

// Bots alive
let alive = 0

function print(msg) {
  //console.log('[Bots Alive: ' + alive + ']\t\t' + msg)
  var Alives = alive <<<--- Says Uncaught ReferenceError: Alives is not defined
}`

I get

**Comment by sandor111** [comment]
@mayed505  Do you have skype? plz add me: sandor,potjer

**Comment by mayed505** [comment]
@sandor111 where are u from on skype?

**Comment by sandor111** [comment]
Netherlands

**Comment by sandor111** [comment]
i typed a , instead of an . I the message above^^ so if you copied that it was wrong

**Comment by mayed505** [comment]
added

**Comment by mayed505** [comment]
@sandor111 are you gonna help me do the code?

**Comment by DeRpYsApLiNg** [comment]
let alive doesn't change once a bot is spawned, it would just stay as a 0

**Comment by dahquan** [comment]
The variable ```alive``` is unused code that I have to clean up
