### ISSUE TITLE
Fix NPM package on dist bot Packet, change to packet

### ISSUE THREAD

**Issue by SrNicolas** [dahquan/rattlesnake#27]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by dahquan** [comment]
I'll update that right now

**Comment by dahquan** [comment]
It's now updated to 0.1 on NPM
