### ISSUE TITLE
Impossible to use the lib.

### ISSUE THREAD

**Issue by SrNicolas** [dahquan/rattlesnake#28]
Hi. Me and a friend developed a script kind of ogar-feeder-bot using this lib. The problem is that its impossible to use the lib due to an error.

const Bot = require('rattlesnake')
and got this error
https://gyazo.com/3c5ef735556b96b5c226d124e7c94894

**Comment by dahquan** [comment]
Did you figure out the problem? Were you using an instance of bot?

**Comment by SrNicolas** [comment]
I can't figure out how works the port of the proxy connect, so that may be the problem with low bots, because it always uses port 80

**Comment by dahquan** [comment]
You can change the port of the proxy by adding ```:[PORT]``` to the ip. So for example:

```
55.33.22.11:8080
```

**Comment by SrNicolas** [comment]
can you explain better plesase?

**Comment by dahquan** [comment]
Inside of proxies.txt, if you have an ip '''4.32.56.1''' but it uses port 8090. This is how you would put it inside proxies.txt:

'''
4.32.56.1:8090
'''

**Comment by SrNicolas** [comment]
I did that, but in src you can clearly see host serverip

port: 80

**Comment by dahquan** [comment]
It uses port 80 by default if none are given.

https://github.com/dahquan/rattlesnake/blob/master/src/bot.js#L67

**Comment by SrNicolas** [comment]
Okay, got it to work, but maybe its my code, when the bot user connects, it starts to create infinite clients and use 100% ram/cpu, maybe its my client, maybe its the lib itself 
and also dahquan, can you add me on skype? skype: nicolasdelito

**Comment by yario-o** [comment]
Close this?

**Comment by l3mpik** [comment]
Yes close, SrNicolas is just kid and want to always sell "noob bots" :D He write only HTML ( very low lvl ) .

**Comment by SrNicolas** [comment]
yo, fuck off.
