### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ElieeCh** [dahquan/rattlesnake#3]
Do you know where this error is coming from ? 
![capture](https://cloud.githubusercontent.com/assets/18157373/15308377/9a7c9d48-1baa-11e6-9517-779da7f23422.PNG)

**Comment by dahquan** [comment]
Yes I do, it's from an unused module I forgot to remove. I'm fixing that right now along with another small problem.

**Comment by ElieeCh** [comment]
Alright, thanks!
