### ISSUE TITLE
Raw MoveTo/FacePosition code

### ISSUE THREAD

**Issue by MrSonicMaster** [dahquan/rattlesnake#31]
Is it possible that you could show nme the raw MoveTo/FacePosition code, not with all of your other packet.put code? 

As in the:
`arr = new Uint8Array(3);`
`arr[0] = opcode;`
`arr[1] = radians;`
`ws.send(arr);`

Like that?

**Comment by dahquan** [comment]
Have you tried taking a look at the Packet class?

**Comment by MrSonicMaster** [comment]
@dahquan your code is confusing, it bounces data to many different files. Anyways, i have located the moveto code myself. Thanks anyways.
