### ISSUE TITLE
Add Socks Proxy Support

### ISSUE THREAD

**Issue by MrSonicMaster** [dahquan/rattlesnake#32]
Add Socks Proxy support in bot.js

at the top, require the Socks module:
`let Socks = require('socks');`

also, add the if mode === socks

     //...
    } else if (mode === 'socks') {
        //console.log('Mode socks, proxy', proxyServer);
        let temp = proxyServer.split(':');
        let socksIp = temp[0]
        let socksPort = temp[1];
        requestOptions.agent = new Socks.Agent({
            proxy: {
                 ipaddress: socksIp,
                port: socksPort,
                type: 5
            }
        });
    }

EDIT: Oh and make sure to actually make the mode socks
replace the 
`var mode = 'http';`
with
`var mode = 'socks';`

EASY WAY: Replace `/dist/bot.js` with this:
http://pastebin.com/ZTV66bWw

**Comment by sandor111** [comment]
Thx <3

**Comment by MrSonicMaster** [comment]
np bro, just had to make some minor changes, i'm a bit new to Github and making the code segments.

**Comment by MrSonicMaster** [comment]
@sandor111 make sure to look at my edits

**Comment by sandor111** [comment]
You can make a pull request :)

**Comment by MrSonicMaster** [comment]
@sandor111 Problem is, i don't know how to XD

**Comment by sandor111** [comment]
😂

**Comment by Wartoz** [comment]
i'm confuse there is two bot.js files into dist folder / and src folder

**Comment by MrSonicMaster** [comment]
@Wartoz in the /src folder

**Comment by XtremePlayzCODE** [comment]
@MrSonicMaster lol mr. bot maker, did you add me on skype yet?

**Comment by XtremePlayzCODE** [comment]
@MrSonicMaster i gave it to you on yt, you never added me though

**Comment by MrSonicMaster** [comment]
@XtremePlayzCODE I did add you, you never accepted

**Comment by anonymousxxx02** [comment]
@MrSonicMaster can you please add bot.js with socks support in pastebin

**Comment by MrSonicMaster** [comment]
@anonymousxxx02 ok sure

Replace /dist/bot.js with this:
http://pastebin.com/ZTV66bWw

**Comment by anonymousxxx02** [comment]
@MrSonicMaster bro can you send me all bot files in my gmail because i have some problem installing npm and other things
anonymousx023x@gmail.com

**Comment by MrSonicMaster** [comment]
@anonymousxxx02 me giving you all my bot files wont help you install NPM and NodeJS, you need to look on the NodeJS website for that.

**Comment by XtremePlayzCODE** [comment]
gonna accept brb

**Comment by anonymousxxx02** [comment]
ok i fix bot but nowsocks i get this error when i use socks 

`

C:\Users\xxx\Desktop\SlitherBots\node_modules\examples>node feed
me.js
Feed Me Bot
1. Open a browser and navigate to http://slither.io
2. Open this script file (examples/feedme.js) and copy the browser code all the
way at the top of the file
3. Go to the developer console then paste the browser code and press enter
4. Login normally and you should see your bots start to connect

** Bots will stay on the same server even if you die and will NOT switch servers
, to stop it press Ctrl+C
[Bots Alive: 0]         Spawning 68 snakes
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
 'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
 'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
 'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
 'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
 'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
 'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
 'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
 'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
 'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
 'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
 'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
 'ECONNRESET' }

`

**Comment by XtremePlayzCODE** [comment]
They aren't good proxys then

**Comment by anonymousxxx02** [comment]
i just check them they work perfect

**Comment by XtremePlayzCODE** [comment]
whats ur skype name then sonic?

**Comment by XtremePlayzCODE** [comment]
i got 3 people wanting to add me

**Comment by anonymousxxx02** [comment]
@XtremePlayzCODE does your bots work with socks??

**Comment by XtremePlayzCODE** [comment]
yeah

**Comment by anonymousxxx02** [comment]
can you send me all bots files please???

**Comment by XtremePlayzCODE** [comment]
nah

**Comment by yario-o** [comment]
@MrSonicMaster you have two github account?

**Comment by yario-o** [comment]
I create a pull request

**Comment by anonymousxxx02** [comment]
@yario-o please help me..when i use the script with socks suport i get this error
`Bots will stay on the same server even if you die and will NOT switch servers
, to stop it press Ctrl+C
[Bots Alive: 0] Spawning 68 snakes
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
'ECONNRESET' }
{ [Error: socket hang up] code: 'ECONNRESET' }
{ [Error: tunneling socket could not be established, cause=socket hang up] code:
'ECONNRESET' }`

**Comment by yario-o** [comment]
What proxies do you use?

**Comment by anonymousxxx02** [comment]
socks 4/5

**Comment by yario-o** [comment]
What website?

**Comment by anonymousxxx02** [comment]
http://www.live-socks.net/

**Comment by yario-o** [comment]
Try with http://vipsocks24.net

**Comment by yario-o** [comment]
Si?

**Comment by anonymousxxx02** [comment]
nothing happend..i get the same problem

**Comment by kurama129** [comment]
Nice work mrsonic

**Comment by mayed505** [comment]
@yario-o I use my proxies from premium.freeproxy.ru/en/  and still have that problem with @anonymousxxx02

**Comment by yario-o** [comment]
Annonymous do you have skype?

**Comment by anonymousxxx02** [comment]
@yario-o i don use skype but if you want you can send me all bot files in my gmail

**Comment by mayed505** [comment]
@yario-o i have skype add me: mayed5011 please tell me whats the problem

**Comment by kurama129** [comment]
Anyone has chither userscript

**Comment by anonymousxxx02** [comment]
@kurama129 you can download from chither.com

**Comment by kurama129** [comment]
Ok

**Comment by MrSonicMaster** [comment]
@yario-o yes, i do have multiple github accounts
@anonymousxxx02 you need good working socks5 proxies in order to not get that error
@kurama129 thanks, it was easy though, i have done this a million times LOL.
@mayed505 try updating your WS library, it may help out, but you should ALWAYS check your proxies before use, many proxies are dead/non functional. Also, make sure to ONLY use socks5, socks4 are not supported.

**Comment by anonymousxxx02** [comment]
Does anyone know how to run bots in c9.io

**Comment by XtremePlayzCODE** [comment]
can't, youll be banned

**Comment by anonymousxxx02** [comment]
@XtremePlayzCODE banned???

**Comment by XtremePlayzCODE** [comment]
@anonymousxxx02 from Cloud9.

**Comment by anonymousxxx02** [comment]
@XtremePlayzCODE i dont care...they already bann my first account...i just want to make bots run in c9.io

**Comment by XtremePlayzCODE** [comment]
Well get banned again and again then

**Comment by kurama129** [comment]
I'll know you mrsonic O_o your the yt guy right

**Comment by anonymousxxx02** [comment]
@MrSonicMaster thanks for sharing script for socks support it work perfect...i just want to ask one thing    what sock type it support sock 4/5 or only socks 5

**Comment by kurama129** [comment]
Only socks  5

**Comment by anonymousxxx02** [comment]
i add another else if with sock type 4 in bot.js and now i get more bots

`} else if (mode === 'socks') {
    //console.log('Mode socks, proxy', proxyServer);
    let temp = proxyServer.split(':');
    let socksIp = temp[0]
    let socksPort = temp[1];
    requestOptions.agent = new Socks.Agent({
        proxy: {
             ipaddress: socksIp,
            port: socksPort,
            type: 4
        }
    });
}` and now i get more bots

**Comment by kurama129** [comment]
You could give me your Skype I'll give you the userscript personnally

**Comment by kurama129** [comment]
Tscript is a basic thing make it yourself  m8

**Comment by Optimusprimeagario** [comment]
STOP ASKING HOW TO GET BOTS ON C9.IO its easy as fu**k

**Comment by XtremePlayzCODE** [comment]
you mean fuck?

**Comment by Optimusprimeagario** [comment]
noo.... O_o

**Comment by MrSonicMaster** [comment]
Ok this is getting off topic, i'm going to close it.

**Comment by sandor111** [comment]
@kurama129 Can you add me on skype please: sandor.potjer
