### ISSUE TITLE
kwebbelkop Skin number?

### ISSUE THREAD

**Issue by Nick8fr32** [dahquan/rattlesnake#35]
Hey I was just wondering if anyone know what the number for the kwebbelkop skin is?

**Comment by mayed505** [comment]
@Nick8fr32 keep trying i think its 39 or 40 since its the last skin released

**Comment by yario-o** [comment]
no it s 37

**Comment by yario-o** [comment]
for now skin id click on custom skin, go to the blue skin(not the light blue) it is the 1 skin and just go right for fin the 2 , 3 ...

**Comment by Nick8fr32** [comment]
@yario-o ohh okay thx i will remember that :)
