### ISSUE TITLE
Feedme

### ISSUE THREAD

**Issue by fadythegamer** [dahquan/rattlesnake#41]
So if i do node feedme.js then doesnt work

**Comment by fadythegamer** [comment]
I'm on windows 10

**Comment by kurama129** [comment]
I'm on windows 10 too I can help you

**Comment by kurama129** [comment]
Node feedme.js isn't enough

**Comment by kurama129** [comment]
Cd server
Node feed.js 
And I think bot.js too
And paste the code in console

**Comment by fadythegamer** [comment]
Dont work

**Comment by mayed505** [comment]
@fadythegamer have you done npm install first?

**Comment by Nick8fr32** [comment]
open a command windoe on the file type `cd examples` and after `node feedme.js`
