### ISSUE TITLE
Stop making stupid issues

### ISSUE THREAD

**Issue by SrNicolas** [dahquan/rattlesnake#43]
First of All
THIS IS NOT A BOT. This is a lib.
second. there is a README.md for something look there before than making a STUPID issue like #40.
third and last. There's 14 watchers(including me) that don't want stupid issues like #40 or #35.

Thanks in advice.

**Comment by kurama129** [comment]
Why the fuck  you care your not the developer here so if you have a problem fuck off  and your issue shows how stupid you are ;)

**Comment by SrNicolas** [comment]
Yes, I'm not, but why the fuck do I need to know the fucking skin number of kwelbpshit? andmany of the watchers don't want to know it too.

**Comment by kurama129** [comment]
Yeah your right there but some are lil  kid's so don't mind them😀 and don't take my comments  seriously it's just a joke

**Comment by ItsVoxility** [comment]
Kurama is right. Kids are going to be kids they don't use common sense . They just do it you know

**Comment by kurama129** [comment]
Yep and they rename this boys and tell that they worked so hard on youtube

**Comment by kurama129** [comment]
Bots

**Comment by dahquan** [comment]
There have been a lot of issues that don't really help the project at all, but also lets not try to spread hate.
