### ISSUE TITLE
How to get the IP

### ISSUE THREAD

**Issue by SrNicolas** [dahquan/rattlesnake#45]
Hi. I'm developing my script with this lib. I already tried with bso.ip but I got no luck. any way to get the server?

**Comment by kurama129** [comment]
Hehe he I got it but I ain't gonna share cuz you make people pay for bots just like Mey bots O_o

**Comment by kurama129** [comment]
I used this to crash slither servers

**Comment by yario-o** [comment]
do you try bso.ip is the ip and bso.po is the port you must do like it : var server = bso.ip + ':' + bso.po

**Comment by anonymousxxx02** [comment]
@kurama129 can you share your script with me

**Comment by kurama129** [comment]
Ok I have script want it guys

**Comment by kurama129** [comment]
Wait I'll post a issue and a pull request

**Comment by SrNicolas** [comment]
Thanks in advice yario.

**Comment by ItsVoxility** [comment]
My phone has been getting spammed for the past 10 mins so ima just join this conversation what script are we talking about?

**Comment by kurama129** [comment]
Userscript

**Comment by kurama129** [comment]
Instead of pasting code code in console I made a script to paste in tamper monkey which reduces pain in the ass
