### ISSUE TITLE
Number of alive dots don't work perfectly

### ISSUE THREAD

**Issue by anonymousxxx02** [dahquan/rattlesnake#46]
bots alive: -60

**Comment by l3mpik** [comment]
Becouse u use bad proxy. Try to find 100% working proxy and problem gone.  Trust me. : )

**Comment by anonymousxxx02** [comment]
@l3mpik i know that but there isn't any way to see only connected bots..
and do you  know any good site for proxy

**Comment by l3mpik** [comment]
@anonymousxxx02  I use : 

http://proxyserverlist-24.blogspot.com/

And : 

http://netghost.wastedwolf.com/

Have Fun! : )

**Comment by anonymousxxx02** [comment]
@l3mpik thanks bro : )

**Comment by yario-o** [comment]
close this issue

**Comment by yario-o** [comment]
This is because it do 
`alive-- `
when proxy disconnect so it do that when proxy don't work

**Comment by anonymousxxx02** [comment]
@yario-o do you know how to fix that???

**Comment by SrNicolas** [comment]
Look at dist/bot.js onClose

**Comment by mayed505** [comment]
@SrNicolas hey :)
