### ISSUE TITLE
Client + Server : ) Like Oger Feeder Bot

### ISSUE THREAD

**Issue by l3mpik** [dahquan/rattlesnake#47]
Today remade little script. No longer uses the GET, all data as position, or the command "speed" are sent by the socket. + Weak gui for a beginning. How I will have more time to refine and give server + client. At the moment, the server receives information such as the name of bots (can be changed during the game), the position, the command "speed". Everything looks like "Ogar feeder bot".

I also added a change in the connection between the local server and VPS.

http://imgur.com/tYlDTtu

**Comment by anonymousxxx02** [comment]
are you gonna share script???

**Comment by Wartoz** [comment]
looks great will you share this project?

**Comment by Wartoz** [comment]
maybe can add bot eat pellets when you press a key too

**Comment by MineMooreALT** [comment]
Please realease :+1: D

**Comment by l3mpik** [comment]
Ye, i share this. But not now i need to make code better and clear. : ) Maybe tommorow ;p

**Comment by MineMooreALT** [comment]
Can i just check it out now? would really appreciate it.

**Comment by l3mpik** [comment]
Give me 10 min and i share this : )

**Comment by MineMooreALT** [comment]
Ok thanks it's 1 am where i live so i gtg soon thanks !!!!

**Comment by anonymousxxx02** [comment]
please share it i want to try this awsome script ;)

**Comment by MineMooreALT** [comment]
He is just give him a bit

**Comment by l3mpik** [comment]
Almost done, just clear script and upload : )

**Comment by MineMooreALT** [comment]
Sorry, i'm confused where do i download this?

**Comment by l3mpik** [comment]
Github. in my profile. But easy give me little time.. haha : )

**Comment by MineMooreALT** [comment]
ok

**Comment by MineMooreALT** [comment]
How much longer so i know i'm very impainent

**Comment by l3mpik** [comment]
Go to my git.

**Comment by MineMooreALT** [comment]
thanks

**Comment by mayed505** [comment]
@l3mpik ca i sue your repo and use it as mine but with alot of features than yours?

**Comment by MineMooreALT** [comment]
What version of node are you using?

**Comment by l3mpik** [comment]
5.7.0
