### ISSUE TITLE
Bots

### ISSUE THREAD

**Issue by ElieeCh** [dahquan/rattlesnake#5]
Just wanted to ask you if you can make the bots more similar to raga.pw bots, so when they get closer to you they try to go for the part close to your head without trying to kill you !
Other than that, amazing work ! Everything worked out amazingly as expected. Thank you so much for sharing the project for free ! :)

**Comment by dahquan** [comment]
I'm not too focused on actually logic of the bot, I kind of want to leave that part up to the people who use the library. Maybe one day I'll try making a more advanced bot, but for now we will have to leave that up to contributors.

**Comment by ElieeCh** [comment]
Alright, thanks!
