### ISSUE TITLE
bots in mobile version

### ISSUE THREAD

**Issue by kurama129** [dahquan/rattlesnake#53]
how are bots based on this working in mobile version of the game

**Comment by dahquan** [comment]
You tested it in mobile? It should still work.

**Comment by kurama129** [comment]
but how can i use it in mobile

**Comment by kurama129** [comment]
our android cant run .js script right

**Comment by kurama129** [comment]
if theres a way to use it tell and when is collide releasing

**Comment by kurama129** [comment]
nvm i found a way 😀it works btw i edited your script too much for getting more bots and used websockets but yours is a great example
