### ISSUE TITLE
Port 1337 Error

### ISSUE THREAD

**Issue by Rassyp** [dahquan/rattlesnake#54]
These bots were working for me a few days ago, now when i try to start the feedme.js, i get this error

http://prntscr.com/b8wgg8

Any help?

**Comment by kurama129** [comment]
redownload and use port 8081

**Comment by anonymousxxx02** [comment]
I also get that error with port 8080 but bots work fine

**Comment by kurama129** [comment]
does bots follow after the error

**Comment by Rassyp** [comment]
Nevermind, fixed it :)
