### ISSUE TITLE
[Off Topic] Created web page 

### ISSUE THREAD

**Issue by SrNicolas** [dahquan/rattlesnake#56]
Hi! I created a webpage that almost always is online that scrapes every hour a new 2000 proxy list.

83.53.79.242/getproxy.PHP?raw&amount=max

**Comment by kurama129** [comment]
umm scrapes from where

**Comment by mayed505** [comment]
@SrNicolas can you send me the files you run on xampp? i really need that too :)

**Comment by l3mpik** [comment]
I see agin meybots. @SrNicolas  STFU!! Bitch! U  nevr be coder, kid. When i mett u first time, u don't have any idea what is VPS ... -,-

**Comment by mayed505** [comment]
@l3mpik lol, are you joking?

**Comment by Wartoz** [comment]
true story

**Comment by mayed505** [comment]
:P

**Comment by l3mpik** [comment]
@mayed505 It's true, I met him when david created hound feeder bot. He asked me to put his boots on the VPS. Nothing could and nothing will not be able to, put just download the script and rename it like his. The whole meybost this shit. SrNicolas can not do programming, has only a buddy at work Piss for him.

**Comment by l3mpik** [comment]
I make bots for free, no for money. Welcome to my git.

**Comment by SrNicolas** [comment]
First of all. I never said that I'm a coder, Second, I probably coded more than you. Third, And yes, I didnt know wut is that, cuz I didn't need to know it. Coding is only a hobby for me.

**Comment by kurama129** [comment]
but your a noob 😑

**Comment by Numan1982** [comment]
Wartoz You Cant Say Shit At All Your Selling Your Shitty Bots Which Are An Open Source. And Your Selling Them For $8 ARE YOU FUCKED? Dont Try And Sell Free Bots And Trying To Act As If You Can Code When You Cant.

**Comment by dahquan** [comment]
Stop with all these off topic toxic issues
