### ISSUE TITLE
random name and random skin

### ISSUE THREAD

**Issue by anonymousxxx02** [dahquan/rattlesnake#57]
add this at feedme.js  at top 
**********************************************************************************************************
var slithernames = {};

slithernames.nameList = [
"nikos","AnonymousBots","xxx2" 
];

slithernames.getRandomName = function() {
return slithernames.nameList[Math.floor((Math.random() * slithernames.nameList.length))];
};
function rskin(){
return Math.floor((Math.random() * 39)+1)};
******************************************************************************************************
and change line 50 and 52 to 
`name: slithernames.getRandomName()`
`skin: rskin()`

**Comment by kurama129** [comment]
i did this long back 😀 but im only trying to find only this how are bots coming in mobile version

**Comment by anonymousxxx02** [comment]
if you make bots run in mobile will you tell me pleasee ??? :)

**Comment by kurama129** [comment]
okie in skype

**Comment by kurama129** [comment]
you like mobile one right me 2😀

**Comment by kurama129** [comment]
found a new thing we cant run bots on mobile and about the bots we see in mobile is because web version and mobile is connected

**Comment by anonymousxxx02** [comment]
@kurama129 sorry bro i dont use skype : (
