### ISSUE TITLE
Error packet

### ISSUE THREAD

**Issue by KrissV2** [dahquan/rattlesnake#6]
Do you know why i have always this error ? 

> Error: Cannot find module './lib/Packet'

**Comment by dahquan** [comment]
What directory are you in and what command are you running?

**Comment by KrissV2** [comment]
i try run feeder from example folder , node feedme

I upload your project, and put command npm install 
No error and now i just try run :)
> /root/snake/examples

Thx for reply

**Comment by dahquan** [comment]
try doing node examples/feedme.js 

If that doesn't work can you take a sreenshot?

**Comment by KrissV2** [comment]
here is screen

> https://snag.gy/iKraXJ.jpg

**Comment by dahquan** [comment]
Are you sure you have all the files installed? can you take a picture of the directory?

**Comment by KrissV2** [comment]
> https://snag.gy/afmDIl.jpg
> https://snag.gy/hu3yQ1.jpg

**Comment by dahquan** [comment]
Hey, try redownloading/cloning the repo again, I think I've added the fix for your issue

**Comment by KrissV2** [comment]
yes , now have info 

> Feed Me Bot
> 1. Open a browser and navigate to http://slither.io
> 2. Open this script file (examples/feedme.js) and copy the browser code all the way at the top of the file
> 3. Go to the developer console then paste the browser code and press enter
> 4. Login normally and you should see your bots start to connect

Then, thank you very much :)
