### ISSUE TITLE
http://slitherbots.tk/ EXPOSED

### ISSUE THREAD

**Issue by XtremePlayzCODE** [dahquan/rattlesnake#60]
http://slitherbots.tk/ COMPELETELY COPIED THIS WITHOUT CREDIT.

**Comment by HLDahquan** [comment]
It's really sad that no credits were given but at the same time not much I can do about it.

**Comment by XtremePlayzCODE** [comment]
Not in their video. Uploading new exposing video soon @ bit.ly/XtrBotz

**Comment by Classicanon** [comment]
actually their vid dose give credit in the description

**Comment by XtremePlayzCODE** [comment]
xd i am proven wrong, closing issue
