### ISSUE TITLE
userscript spamming with errors

### ISSUE THREAD

**Issue by mayed505** [dahquan/rattlesnake#64]
my console is spamming with these errors https://gyazo.com/c8f5284ccafc272305b75b156788158b
because of https://gyazo.com/5ed8249290fa76e097f6471dc9e9e7f4

**Comment by XtremePlayzCODE** [comment]
```javascript
var x = window["snake"].xx;
var y = window["snake"].yy;

socket.emit('pos', x, y);
```

**Comment by XtremePlayzCODE** [comment]
Also where did you get that userscript?

**Comment by mayed505** [comment]
@XtremePlayzCODE i coded it my own and thanks for the answer.

**Comment by XtremePlayzCODE** [comment]
@mayed505 Can you please share it with me, I wanna see this script

**Comment by XtremePlayzCODE** [comment]
I mean, the whole bot script. This rattlesnake feedme bot sucks so I want to see if yours can be better

**Comment by mayed505** [comment]
@XtremePlayzCODE cant its private project will be going on.

**Comment by XtremePlayzCODE** [comment]
kk, just wanting to see

**Comment by mayed505** [comment]
@XtremePlayzCODE it doesnt work still getting that error :(

**Comment by mayed505** [comment]
@XtremePlayzCODE the problem is from this code. `setInterval(function() {
    if(snake) {
        document.getElementById("MY VARIABLE").innerHTML = "" + Math.floor(15 * (fpsls[snake.sct] + ["snake"].fam / fmlts[snake.sct] - 1) - 5) / 1
    }
}, 100);`

this one gets slither length score

**Comment by XtremePlayzCODE** [comment]
use `window["snake"]` or `window.snake` instead of `snake`

**Comment by mayed505** [comment]
@XtremePlayzCODE thank ill try

**Comment by mayed505** [comment]
@XtremePlayzCODE do you have skype i have something important i need help.

**Comment by XtremePlayzCODE** [comment]
sure, xtremeplayzyt is my skype
