### ISSUE TITLE
Encode a javascipt and cant be decoded?

### ISSUE THREAD

**Issue by mayed505** [dahquan/rattlesnake#66]
hi all, i know its not an issue but this is important. i want to encode my javascript and i dont want it to be decoded and stolen by youtube skids. Thanks.

**Comment by WJKH** [comment]
No, it's not possible. You can obfuscate it, but there's no way of protecting it completely.

**Comment by mayed505** [comment]
@WJKH aww.

**Comment by yario-o** [comment]
Use jxcore ?

**Comment by yario-o** [comment]
Use jxcore
