### ISSUE TITLE
Is There an event when bot die ?

### ISSUE THREAD

**Issue by yario-o** [dahquan/rattlesnake#67]
Is There an event when bot die ?
I Want to do : 
`bot.on('TheEvent', function() {`

**Comment by mayed505** [comment]
@yario-o i wish there was. so i can reconnect the bots on death.

**Comment by yario-o** [comment]
The Bots reconnect automatically : 
`const bot = new Bot({
        name: process.env.SLITHER_SERVER_NAME || 'www.slither.gg',
        reconnect: true, // Here the bots reconnect automatically
        skin: skin,
        server: server
      })`

**Comment by mayed505** [comment]
@yario-o thanks.

**Comment by yario-o** [comment]
So. There is an event when bot die?

**Comment by mayed505** [comment]
@yario-o i dont think so if yes then what will it be for?

**Comment by devesh457** [comment]
https://github.com/ClitherProject/Slither.io-Protocol/blob/master/Protocol.md#type_v_detail
Check here

**Comment by yario-o** [comment]
Because the number of bot alive is not perfect. Look : 
bot.on('disconnect', function() {
        alive--
        print(bot.name + ' died')
      })
It do  `alive--` when bot disconnect so when proxy disconnect is do `alive--`

**Comment by yario-o** [comment]
@devesh457 Thx

**Comment by yario-o** [comment]
EDIT : I just find the dead fonction now by number of bots alive can't be negative Just replace : 
bot.on('disconnect', function() {
        alive--
        print(bot.name + ' died')
      })
To : 
bot.on('dead', function() {
        alive--
        print(bot.name + ' died')
      })
