### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by glenclark** [dahquan/rattlesnake#7]
this is what i get when i run it 

[root@vps79645 rattlesnake]# node examples/feedme.js

/root/rattlesnake/examples/feedme.js:16
const Bot = require('../dist')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by dahquan** [comment]
What version of node are you using?

**Comment by glenclark** [comment]
latest i believe

**Comment by dahquan** [comment]
Can you tell me the output of

```node -v```?

**Comment by glenclark** [comment]
yes one sec

**Comment by glenclark** [comment]
v0.10.42

**Comment by dahquan** [comment]
Looks like you need to update your node version, the latest right now is version 6.

**Comment by glenclark** [comment]
ok what is mine like not even 1 XD?

**Comment by glenclark** [comment]
how do i update it on linux vps ?

**Comment by dahquan** [comment]
Take a look [here](https://nodejs.org/en/download/package-manager/)

**Comment by glenclark** [comment]
it works now but now i get an error on console

**Comment by dahquan** [comment]
What error?

**Comment by glenclark** [comment]
VM19754:1 GET http://127.0.0.1:1337/inject net::ERR_CONNECTION_REFUSED

**Comment by dahquan** [comment]
You have to change the ip to the server if you aren't going to be running it locally

**Comment by glenclark** [comment]
i did but it still says it

**Comment by dahquan** [comment]
Open ```examples/feedme.js``` and replace all ```127.0.0.1``` with the ip.

**Comment by glenclark** [comment]
yea i did but it still doesnt work

**Comment by glenclark** [comment]
GET http://149.56.108.92:1337/inject net::ERR_CONNECTION_TIMED_OUT

**Comment by dahquan** [comment]
Did you make sure you are port forwarding correctly? http://www.yougetsignal.com/tools/open-ports/

**Comment by glenclark** [comment]
ok it shows its closed

**Comment by glenclark** [comment]
how do i open it on centos

**Comment by dahquan** [comment]
http://ask.xmodulo.com/open-port-firewall-centos-rhel.html

I don't think the questions you are asking have to do with the library any more, you should ask misc questions here: https://gitter.im/dahquan/rattlesnake?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
