### ISSUE TITLE
c9.io

### ISSUE THREAD

**Issue by gamer2331** [dahquan/rattlesnake#73]
The bots won't run

**Comment by gamer2331** [comment]
Can someone help me

**Comment by anonymousxxx02** [comment]
Change all the ports to 8080

**Comment by gamer2331** [comment]
i did

**Comment by gamer2331** [comment]
Not worked

**Comment by Numan1982** [comment]
dont change port in server.js

**Comment by gamer2331** [comment]
I didn't do that

**Comment by gamer2331** [comment]
I did npm install and (npm install socket.io in node_modules)

**Comment by Numan1982** [comment]
hm then im not sure. did u change the ip in tamper?

**Comment by gamer2331** [comment]
? I dont use it with tamper just without a script

**Comment by Numan1982** [comment]
tell me c9 link
ill try and do it.

**Comment by gamer2331** [comment]
https://ide.c9.io/primalfady/fady

**Comment by Numan1982** [comment]
give me acess

**Comment by gamer2331** [comment]
how

**Comment by Numan1982** [comment]
;/ go on collaberate then do it

**Comment by gamer2331** [comment]
did it

**Comment by anonymousxxx02** [comment]
@gamer2331 bro give me c9.io link and rw permision and i will fixit for you

**Comment by gamer2331** [comment]
Tommorow

**Comment by gamer2331** [comment]
You here?

**Comment by yario-o** [comment]
I m here

**Comment by gamer2331** [comment]
can you fix it for me please

**Comment by gamer2331** [comment]
i can send link

**Comment by yario-o** [comment]
Yes send

**Comment by gamer2331** [comment]
https://ide.c9.io/primalfady/fady

**Comment by yario-o** [comment]
So?

**Comment by gamer2331** [comment]
can you help me the bots dont work for me ;(

**Comment by gamer2331** [comment]
they dont run

**Comment by yario-o** [comment]
There is an error?

**Comment by gamer2331** [comment]
no they just dont run
