### ISSUE TITLE
How to Use This 

### ISSUE THREAD

**Issue by devesh457** [dahquan/rattlesnake#8]
Hello,
I would Like Give The Feedback But How To Use This?

**Comment by dahquan** [comment]
Please take a look at the documentation

http://dahquan.github.io/rattlesnake/examples.html

**Comment by devesh457** [comment]
Thanks For The Reply i Followed Everything Yeah they spawned once but now its shows error on my command promt screen  "tunneling socket could not be established "

**Comment by dahquan** [comment]
That means the proxy servers you are using aren't as good, try using better ones

**Comment by devesh457** [comment]
can you give me some site where i get good proxies !!! (Would Be Very Thankfull)

**Comment by dahquan** [comment]
Please use issues for questions that relate to the library.
