### ISSUE TITLE
if a proxy not working move to anorther file and reconnect anorther bot when its offline.

### ISSUE THREAD

**Issue by mastkilxp** [dahquan/rattlesnake#82]
is this already included in the code? so for example if a proxy doesnt work its gonna bring it for example to: offproxies.txt. and reconnect a bot when a proxy goes offline from proxies.txt. has this already coded in the script? if not i would like to do this. if this is possible. except if someone else is already doing this

**Comment by WJKH** [comment]
This script isn't a proxy checker.

**Comment by mastkilxp** [comment]
did i just said it was? or did i just said i want to make one in the script if there isnt one yet?

**Comment by WJKH** [comment]
You only opened an issue to said something no related to the project.

Do you know how to use issues here?
Do you need some tutorial?

**Comment by mastkilxp** [comment]
well nevermind. i keep this project private cus i think it would be OP i just asked a question which anyone who worked on this could just say: yes u can do this. or no dont do this cus...

for people that dont know what i meant this is what i meant.

theres a file called proxies.txt, so im gonna code it so its going to get proxies from proxies.txt when any proxy gives an error i make it so it recognize as offline so it transport to anorther file called for example: offproxies.txt so you could put in like 10k proxies when you need one and a bot goes offline the code takes anorther proxy and reconnect them. but nevermind i do this private and i wont share since this could be OP sorry all.

**Comment by WJKH** [comment]
If you know how do it, you will not ask if it's possible or not.
Good luck doing it.

**Comment by mastkilxp** [comment]
i asked if this was already coded in yet or not. lol. but this is closed.

**Comment by WJKH** [comment]
In the file README.md you have the Features section.
Also you can read the source code if you know how do it.

**Comment by mastkilxp** [comment]
ah thankyou!

**Comment by ravyn120** [comment]
@mastkilxp This is simple AF lol. Just find a node proxy checker with export options and start that before the feedme.js with a cmd command.
