### ISSUE TITLE
VPS Support

### ISSUE THREAD

**Issue by YTpuffer** [dahquan/rattlesnake#9]
I tried to run the script on my VPS (windows) and got the following error:

> XMLHttpRequest cannot load http://xxx:1337/inject/goto?x=35137.54922322851&&y=14828.182821132874. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://slither.io' is therefore not allowed access. The response had HTTP status code 404.

I changed the code what you have to paste in the console to:

> var xhttp=new XMLHttpRequest;xhttp.onreadystatechange=function(){4==xhttp.readyState&&200==xhttp.status&&eval(xhttp.responseText)},xhttp.open("GET","http://xxx:1337/inject",!0),xhttp.send();

Thanks for your help!

**Comment by YTpuffer** [comment]
Do i need to change to port to: 8081 maybe?

**Comment by SrNicolas** [comment]
Try it

**Comment by dahquan** [comment]
Have you changed all the ips in ```examples/feedme.js``` to the new one?

Go in there are replace 127.0.0.1 with it

**Comment by SrNicolas** [comment]
I did, not working

Timed Out

**Comment by dahquan** [comment]
That first url isn't even correct, it should just be 

http://149.202.241.161:1337/inject

**Comment by SrNicolas** [comment]
Puffer Im recommend to remove the IP of ur server, Using bots from ur server lolz

**Comment by SrNicolas** [comment]
@dahquan its not working still.

**Comment by dahquan** [comment]
Are you using the same ip as him?

**Comment by SrNicolas** [comment]
Yes, bcuz 4 dem lolz, and in my own server, doesnt work either.

**Comment by dahquan** [comment]
I just tested using his url and it worked fine for me.

Just go to http://slither.io and paste in the inject script:

```
var xhttp=new XMLHttpRequest;xhttp.onreadystatechange=function(){4==xhttp.readyState&&200==xhttp.status&&eval(xhttp.responseText)},xhttp.open("GET","http://xxx:1337/inject",!0),xhttp.send();
```

**Comment by YTpuffer** [comment]
So this must be correct:

var xhttp=new XMLHttpRequest;xhttp.onreadystatechange=function(){4==xhttp.readyState&&200==xhttp.status&&eval(xhttp.responseText)},xhttp.open("GET","http://149.202.241.161:1337/inject",!0),xhttp.send();

**Comment by dahquan** [comment]
Yes, just make sure it's portforwarded

**Comment by YTpuffer** [comment]
What port do i forward? :1337 and do i have to change all the IP's in the feedme.js too?

**Comment by SrNicolas** [comment]
Yes.

**Comment by SrNicolas** [comment]
Dah, I could make a tampermonkey script or an extension

**Comment by YTpuffer** [comment]
Sahquan now remove my IP please

**Comment by YTpuffer** [comment]
Still doesnt works.. i got the same error as before

**Comment by SrNicolas** [comment]
Me too

**Comment by dahquan** [comment]
I'll further assist you on the gitter, check there

**Comment by YTpuffer** [comment]
What do i have to forward inbound or outbound and TCP or UDP

**Comment by SrNicolas** [comment]
Both

**Comment by YTpuffer** [comment]
I did them all now.. still not working

**Comment by dahquan** [comment]
Talk to me on [here](https://gitter.im/dahquan/rattlesnake)
