### ISSUE TITLE
problem with connect

### ISSUE THREAD

**Issue by kurama129** [dahquan/rattlesnake#91]
Hello all, I’m have discovered a problem, so when you join the first server the first time bots join fine but when you die, you join a new server right?… So bots comes to new server but heres the problem: the bots go on old_server and new_server at the same time which causes bots not to follow on death or not even reconnect since it will be back to old_server. So what i have found is that we need to disconnect the proxies that are connected to old_server and reconnect it to new_server proxy/server i should say i couldn’t find the right code to do it. So can anyone try to help?

**Comment by WJKH** [comment]
Read my comment here https://github.com/dahquan/rattlesnake/issues/61#issuecomment-223440725

**Comment by kurama129** [comment]
im noob can you give your files in skype or send link to download in kgamingforfun@gmail.com gmail

**Comment by WJKH** [comment]
Just add it before to call spawn function or at the begin of spawn function (line 102 at feedme.js in examples).

```
bots.forEach(function(bot) {
    bot.close()
})
```
